// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2GLqin798LzMxCzZgSv2cEUQB6ouL7b0',
    appId: '1:285673750959:web:dc2cca76edcc42de272f5a',
    messagingSenderId: '285673750959',
    projectId: 'smartway-app',
    authDomain: 'smartway-app.firebaseapp.com',
    storageBucket: 'smartway-app.appspot.com',
    measurementId: 'G-3KT6HY8MZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIdQk7cs9vVj2IFtODrSXCjvkefpDGUMY',
    appId: '1:285673750959:android:db47b5d865c90129272f5a',
    messagingSenderId: '285673750959',
    projectId: 'smartway-app',
    storageBucket: 'smartway-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9VLGTwda8tiiWMOHBsViJuThDjQugKIc',
    appId: '1:285673750959:ios:67465dcafe1d15a7272f5a',
    messagingSenderId: '285673750959',
    projectId: 'smartway-app',
    storageBucket: 'smartway-app.appspot.com',
    iosBundleId: 'com.voxtron.taskmanagementstu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9VLGTwda8tiiWMOHBsViJuThDjQugKIc',
    appId: '1:285673750959:ios:9e3a96ca850e5a68272f5a',
    messagingSenderId: '285673750959',
    projectId: 'smartway-app',
    storageBucket: 'smartway-app.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2GLqin798LzMxCzZgSv2cEUQB6ouL7b0',
    appId: '1:285673750959:web:083c0c2bcfd9d4e7272f5a',
    messagingSenderId: '285673750959',
    projectId: 'smartway-app',
    authDomain: 'smartway-app.firebaseapp.com',
    storageBucket: 'smartway-app.appspot.com',
    measurementId: 'G-8K1ETBE030',
  );
}
